spring.application.name=managmentsystem


spring.app.jwtSecret=YjRjYjg4YzJlZmI3YjYzNWE0MGEwMjM2N2VmNDUyMzZkNjgzOTY4NTRmMjdiYjE0Y2Y1ZjIwMGYxZGYzM2NjYTgxYTlhNzM1MGFhZDBjMTk5MjUxMTZhM2ExNTk3NjA0ZDM4NjAwNzRmN2ZkOThkOWI4YThiMTZlMTVhYjFiMGY=
spring.app.jwtExpirationMs=3000000
spring.jewelry.app.jwtCookieName=jewelryC0ok13

logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss

# ================ H2 CONSOLE =======================
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:test


# FOR AMAZON BEANSTALK
server.port=5000

# ============================= POSTGRESQL ================================================================
#spring.datasource.url=jdbc:postgresql://database-jewelry-postgresql.cyh8s28iyjsh.us-east-1.rds.amazonaws.com:5432/Jewelry
spring.datasource.username=postgres
spring.datasource.password=Johancito7803

# POSTGRESQL RDS DEPLOYED
spring.datasource.url=jdbc:postgresql://database-jewelry-postgresql.cyh8s28iyjsh.us-east-1.rds.amazonaws.com:5432/postgres
#spring.datasource.password=Johancito7803


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ================== LOGGING ===================================
logging.level.org.springframework=DEBUG
logging.level.com.jewelry.managmentsystem=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Esto te dira a que URL se esta conectando la app al arrancar
logging.level.org.springframework.jdbc.datasource.DriverManagerDataSource=DEBUG