spring.application.name=managementsystem


spring.app.jwtSecret=YjRjYjg4YzJlZmI3YjYzNWE0MGEwMjM2N2VmNDUyMzZkNjgzOTY4NTRmMjdiYjE0Y2Y1ZjIwMGYxZGYzM2NjYTgxYTlhNzM1MGFhZDBjMTk5MjUxMTZhM2ExNTk3NjA0ZDM4NjAwNzRmN2ZkOThkOWI4YThiMTZlMTVhYjFiMGY=
spring.app.jwtExpirationMs=3000000
spring.jewelry.app.jwtCookieName=jewelryC0ok13
