spring.application.name=managementsystem


spring.app.jwtSecret=YjRjYjg4YzJlZmI3YjYzNWE0MGEwMjM2N2VmNDUyMzZkNjgzOTY4NTRmMjdiYjE0Y2Y1ZjIwMGYxZGYzM2NjYTgxYTlhNzM1MGFhZDBjMTk5MjUxMTZhM2ExNTk3NjA0ZDM4NjAwNzRmN2ZkOThkOWI4YThiMTZlMTVhYjFiMGY=
spring.app.jwtExpirationMs=3000000
spring.jewelry.app.jwtCookieName=jewelryC0ok13

logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:test

# Loguea todo lo relacionado con el manejo de peticiones web
logging.level.org.springframework.web=DEBUG
# Loguea cada paso de la cadena de filtros de seguridad (CORS, Auth, etc.)
logging.level.org.springframework.security=DEBUG
# Si usas Hibernate, esto te dirá si la consulta SQL falló
logging.level.org.hibernate.SQL=DEBUG

# POSTGRESQL CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/Jewelry
spring.datasource.username=postgres
spring.datasource.password=johancito7803
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate/JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
